language: python
python:
  - 2.6
  - 2.7
  - 3.2
install:
  - pip install --use-mirrors -r requirements.txt
  - python setup.py install
script:
  - coverage run setup.py test
  - coverage report --include="begin*"
notifications:
    email: aaron.iles+travis-ci@gmail.com
